development:
  dialect: postgres
  datasource: host=localhost port=5432 user=ryan password=postgres dbname=timewise sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost port=5432 user=ryan password= dbname=timewise sslmode=disable
  dir: migrations
  table: migrations