development:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=1 dbname=trainer sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=1 dbname=trainer sslmode=disable
  dir: migrations
  table: migrations